### ISSUE TITLE
binding.node is not a valid Win32 application

### ISSUE THREAD

**Issue by TusharDasMe** [bakoushin/self-driving-car-javascript#7]
Error: \\?\C:\Users\Tushar_Das\Desktop\project\self-driving-car-javascript-master\node_modules\@tensorflow\tfjs-node\lib\napi-v6\tfjs_binding.node is not a valid Win32 application.
\\?\C:\Users\Tushar_Das\Desktop\project\self-driving-car-javascript-master\node_modules\@tensorflow\tfjs-node\lib\napi-v6\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Tushar_Das\Desktop\project\self-driving-car-javascript-master\node_modules\@tensorflow\tfjs-node\dist\index.js:58:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

**Comment by TusharDasMe** [comment]
iam using node 14.16.1

**Comment by bakoushin** [comment]
I just tested on 14.16.1 and it works fine.
It seems that something is wrong with the TensorFlow package installed. Try running the following command as they [suggest](https://github.com/tensorflow/tfjs/issues/2046):

`npm rebuild @tensorflow/tfjs-node --build-from-source`

**Comment by TusharDasMe** [comment]
its not working .
can u tell me all the packages and requirement needed for making this project from scratch....

**Comment by TusharDasMe** [comment]
while running the cammand "npm rebuild @tensorflow/tfjs-node --build-from-source"


npm ERR! code 1
npm ERR! path /mnt/c/Users/Tushar_Das/Desktop/project/self-driving-car-javascript-master/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v14.17.0/node-v14.17.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.17.0/node-v14.17.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v14.17.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.17.0/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/tushar/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/mnt/c/Users/Tushar_Das/Desktop/project/self-driving-car-javascript-master/node_modules/@tensorflow/tfjs-node/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tushar/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/tushar/.cache/node-gyp/14.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/tushar/.cache/node-gyp/14.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/tushar/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/tushar/.cache/node-gyp/14.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/mnt/c/Users/Tushar_Das/Desktop/project/self-driving-car-javascript-master/node_modules/@tensorflow/tfjs-node',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/tushar/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 4.4.0-19041-Microsoft
npm ERR! gyp ERR! command "/home/tushar/.nvm/versions/node/v14.17.0/bin/node" "/home/tushar/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /mnt/c/Users/Tushar_Das/Desktop/project/self-driving-car-javascript-master/node_modules/@tensorflow/tfjs-node
npm ERR! gyp ERR! node -v v14.17.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tushar/.npm/_logs/2021-05-12T02_33_23_421Z-debug.log

**Comment by TusharDasMe** [comment]
ok now i just updated  TensorFlow then that error is no more. But 

tushar@DESKTOP-8PO19J8:/mnt/c/Users/Tushar_Das/Desktop/project/self-driving-car-javascript-master$  node train.js --data C:\Users\Tushar_Das\Desktop\project\self-driving-car-javascript-master\data --epochs 3
internal/modules/cjs/loader.js:1127
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libtensorflow.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/mnt/c/Users/Tushar_Das/Desktop/project/self-driving-car-javascript-master/node_modules/@tensorflow/tfjs-node/dist/index.js:58:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)

**Comment by bakoushin** [comment]
Again, seems something is wrong with TF installation. 
Probably it is worth do delete `node_modules` and start the installation over again.

**Comment by TusharDasMe** [comment]
now change my os form windows to kali linux and i coped the data from windows to train in kali linux but there also have some error 
 
error:

(kali㉿kali)-[~/Desktop/self-driving-car-javascript-master]
└─$ node train.js --data ~/Desktop/self-driving-car-javascript-master/data --epochs 3                                                        
2021-05-14 17:26:41.576460: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1795885000 Hz
2021-05-14 17:26:41.577120: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c9fa4b30d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-05-14 17:26:41.577172: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
(node:39818) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/kali/Desktop/self-driving-car-javascript-master/data/driving_log.csv'
(node:39818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bakoushin** [comment]
Ensure that file `/home/kali/Desktop/self-driving-car-javascript-master/data/driving_log.csv` exists. 
It's complaining because it can't find this file.

**Comment by bakoushin** [comment]
Closing due to inactivity. Feel free to reopen if you have further questions.
